cloud:
  aws:
    region:
      auto: false
      static: us-east-2
    credentials:      access-key: 
      secret-key: 
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/400585344349/awsSNSQueue
      
    